# Generated by Django 3.2.4 on 2021-07-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210705_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
